model = "F5TTS_v1_Base_multilingual_full_catada_sft"

model_cfg = ""
srp_model_cfg = ""

ckpt_file = ""
srp_ckpt_file = ""

ref_audio = "infer/examples/multitest/basic_ref_en.wav"
ref_text = ""

lang = "zh"

gen_text = "我是一个多语言语音合成工具"
gen_file = ""

output_dir = "tests"
output_file = "output_test.wav"

remove_silence = false
save_chunk = false

vocoder_name = "vocos"
load_vocoder_from_local = true
vocab_file = ""

target_rms = 0.1
cross_fade_duration = 0.15
nfe_step = 32
cfg_strength = 2.0
sway_sampling_coef = -1.0
speed = 1.0
